Correct Typo error
chrisant996/clink pull request #470
Opened 2023-07-11 09:21 UTC by learninguser

There is a typo error displayed in the description when we run `clink autorun --help` command on Windows 11.

2023-07-11 10:05 UTC, chrisant996 commented
Indeed! The typo was introduced 7 years ago in commit c248c4c.

Looking at that commit, it's clear that the intended word was "correct", not "current". Can you update the PR?

Thanks for catching it!

2023-07-11 10:07 UTC, chrisant996 requested changes

2023-07-11 10:07 UTC, chrisant996 commented on clink/app/src/loader/autorun.cpp
> +        "it starts. The 'install/uninstall' verbs add/remove the current command to run\n"
The intended word was "correct", instead of "current" (see commit c248c4c, which introduced the typo).

2023-07-11 10:11 UTC, learninguser reviewed
Yes, I think it should be correct instead of current

2023-07-11 10:17 UTC, merged

2023-08-09 14:08 UTC, mikebeaton commented
If anyone else arrives here, to possibly save a minor amount of work with `git blame`, the typo was introduced 7 years ago in d3f3700a79bf72af8c71fac147813ef736338dc4. (Typo in the comment about the typo, I guess. 😉)